/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A gym environment handle: construct from a spec JSON, then drive it with
 * command JSONs (`load`, `reset`, `step`, `spec`, `version`).
 */
export declare class Env {
  /** Construct from an `EnvSpec` JSON string. */
  constructor(specJson: string)
  /** Apply a command JSON and return the response JSON string. */
  command(cmdJson: string): string
  /** The gym-core version. */
  version(): string
}
