/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/**
 * A gym environment handle: construct from a spec JSON, then drive it with
 * command JSONs (`load`, `reset`, `step`, `spec`, `version`).
 */
export declare class Env {
  /** Construct from an `EnvSpec` JSON string. */
  constructor(specJson: string)
  /** Apply a command JSON and return the response JSON string. */
  command(cmdJson: string): string
  /** The wickra-gym-core version. */
  version(): string
}
